// Build the browser-facing "three" module out of the installed three.js plus the
// legacy names mind-ar 1.2.5 still imports.
//
// Why a shim rather than pinning an old three.js:
//   - mind-ar 1.2.5 (published 2023) imports `sRGBEncoding`, which three.js removed
//     after r164.
//   - Downgrading three.js would mean shipping a two-year-old renderer.
//   - The shim keeps one modern three.js install and exposes the removed constant,
//     so mind-ar's `import { sRGBEncoding } from "three"` resolves.
//
// Two mind-ar DIST statements also need a runtime guard, because three no longer has
// `WebGLRenderer.outputEncoding` and throws "Cannot set properties of undefined":
//   1. `this.renderer.outputEncoding = sRGBEncoding`
//   2. `this.renderer.addEventListener("change", ...)` (legacy encoding listener)
// They are patched to be defensive instead of being deleted, so behavior is unchanged
// on old three.js and harmless on new.
//
// The patch is applied to a COPY in public/vendor/ -- node_modules is never touched,
// and `npm run vendor` reproduces the result from scratch.

import { mkdir, copyFile, readFile, writeFile, access } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const vendorDir = join(root, "public", "vendor");
const nodeModules = join(root, "node_modules");

const exists = async (p) => {
  try {
    await access(p);
    return true;
  } catch {
    return false;
  }
};

await mkdir(join(vendorDir, "three-addons", "renderers"), { recursive: true });
await mkdir(join(vendorDir, "mindar-extract"), { recursive: true });

// ---------------------------------------------------------------- copied assets
const copies = [
  ["three/build/three.module.js", "three.module.js", true],
  ["three/build/three.core.js", "three.core.js", false],
  // mind-ar's render bundle imports CSS3DRenderer even though this project uses no CSS3D
  // anchors, so it must be present or the bundle fails to link.
  [
    "three/examples/jsm/renderers/CSS3DRenderer.js",
    "three-addons/renderers/CSS3DRenderer.js",
    true,
  ],
  ["mind-ar/dist/mindar-image-three.prod.js", "mindar-image-three.prod.js", true],
  ["mind-ar/dist/controller-mGt1s8dJ.js", "controller-mGt1s8dJ.js", true],
  ["mind-ar/dist/ui-fBadYuor.js", "ui-fBadYuor.js", true],

  // The compiler bundle, loaded by a classic Worker via importScripts. Separate from the
  // render bundle above so the AR viewer never pays for @tensorflow/tfjs: only the upload
  // page's compile worker does, and only after the cheap pre-check has passed.
  ["mind-ar/dist/mindar-image.prod.js", "mindar-image-compile.js", true],

  // mind-ar's tracking-feature extractor, vendored on its own.
  //
  // Why: it is the exact algorithm that decides whether a photo is trackable, so using it
  // gives a ground-truth answer instead of a stand-in heuristic. Critically, these two
  // files import NOTHING but each other -- no @tensorflow/tfjs, no canvas. That lets the
  // upload page's pre-check run in a worker without pulling mind-ar's 2MB+ detector and
  // tfjs bundle (which the full compiler does need, and which we only load once the
  // pre-check has passed).
  ["mind-ar/src/image-target/tracker/extract.js", "mindar-extract/extract.js", true],
  ["mind-ar/src/image-target/utils/cumsum.js", "mindar-extract/cumsum.js", true],
];

const problems = [];
for (const [from, to, required] of copies) {
  const src = join(nodeModules, from);
  if (!(await exists(src))) {
    if (required) problems.push(`required asset missing: node_modules/${from}`);
    else console.log(`[vendor] skip (optional, absent): ${from}`);
    continue;
  }
  await copyFile(src, join(vendorDir, to));
  console.log(`[vendor] ok  ${to}`);
}

// --------------------------------------------------- three.js compatibility shim
// `export *` forwards every current three.js export, so we only hand-maintain the
// legacy additions instead of a 600KB symbol list.
const shim = `// AUTO-GENERATED by scripts/sync-vendor.mjs -- do not edit by hand.
//
// Compatibility layer for mind-ar 1.2.5, which was written against three.js r164 or
// earlier. It re-exports the installed three.js unchanged and adds back the legacy
// names mind-ar still imports.
//
// Everything here is inert on modern three.js:
//   - sRGBEncoding is a numeric placeholder (3001 = the old constant's value).
//     Modern three.js defaults WebGLRenderer to sRGB output already, so nothing needs
//     to be configured; the value exists purely so the import statement resolves.
export * from "./three.module.js";

/** Legacy three.js color-space constant, removed after r164. Value preserved for compatibility. */
export const sRGBEncoding = 3001;

/** Legacy alias. */
export const LinearEncoding = 3000;
`;
await writeFile(join(vendorDir, "three.shim.js"), shim);
console.log("[vendor] ok  three.shim.js (compat shim)");

// ------------------------------------------------------------- mind-ar dist patch
//
// Patch: legacy `renderer.outputEncoding = sRGBEncoding`.
//
// mind-ar 1.2.5 predates three.js r165, which deleted both the property and the
// constant. Assigning to a property that no longer exists throws
// "Cannot set properties of undefined". The replacement keeps the original intent
// (opt into sRGB output) while tolerating modern three.js, where sRGB is already the
// default. It is written defensively rather than deleted so behaviour is unchanged if
// anyone runs this against an older three.js.
//
// Applied to every mind-ar dist bundle that constructs a WebGLRenderer.
const PATCH_TARGETS = ["mindar-image-three.prod.js"];

// The expression may be a member chain (`this.renderer`), not a bare identifier.
// The minified dist chains assignments with commas, so the statement is
// `a.b = c,` rather than `a.b = c;` -- do not anchor on the semicolon.
//
// The replacement is itself a comma expression, NOT a statement. Appending a semicolon
// here would terminate the surrounding comma chain mid-expression and make the whole
// bundle a syntax error:
//     this.a = 1, (...);, this.b = 2      <-- invalid
//     this.a = 1, (...), this.b = 2       <-- valid
const outputEncodingRe = /((?:[\w$]+\.)*[\w$]+)\.outputEncoding\s*=\s*([\w$]+)(?=\s*[,;])/g;

for (const name of PATCH_TARGETS) {
  const target = join(vendorDir, name);
  const original = await readFile(target, "utf8");
  let patched = original;
  const sites = [];

  patched = patched.replace(outputEncodingRe, (match, receiver, value) => {
    sites.push(`guarded ${receiver}.outputEncoding assignment`);
    return `(("outputEncoding" in ${receiver}) && (${receiver}.outputEncoding = ${value}))`;
  });

  if (sites.length === 0) {
    console.log(`[vendor] ${name}: no patching needed`);
    continue;
  }
  await writeFile(target, patched);
  console.log(`[vendor] patched ${name} (${sites.length} site(s)):`);
  for (const site of [...new Set(sites)]) console.log(`         - ${site}`);
  console.log(
    `         size ${original.length} -> ${patched.length} bytes (+${patched.length - original.length})`
  );
}

// Sanity check: if three.js ever regains these names the shim becomes misleading, so say
// so rather than silently carrying dead compatibility code.
const threeSource = await readFile(join(vendorDir, "three.module.js"), "utf8");
const exportBlock = threeSource.slice(threeSource.lastIndexOf("export {"));
if (/\bsRGBEncoding\b/.test(exportBlock)) {
  console.warn(
    "[vendor] note: three.js now exports sRGBEncoding again -- the shim's placeholder " +
      "constant in three.shim.js is redundant and should be removed."
  );
}

// ------------------------------------------------------- vendored extractor patch
//
// mind-ar's `extract.js` imports its sibling with a path that reflects mind-ar's OWN source
// layout: `../utils/cumsum.js`. In our flattened vendor layout that resolves to
// `/vendor/utils/cumsum.js`, which does not exist -- the browser then refuses the whole
// module and the pre-check dies. Rewrite it to the sibling it actually ships next to.
//
// This is exactly the class of bug a browser catches instantly and a naive static check
// misses, which is why check-frontend.mjs now resolves imports RECURSIVELY.
const EXTRACT_TARGET = join(vendorDir, "mindar-extract", "extract.js");
const EXTRACT_IMPORT_FIX = [
  {
    from: /from\s*["']\.\.\/utils\/cumsum\.js["']/g,
    to: 'from "./cumsum.js"',
    note: "rewrote ../utils/cumsum.js -> ./cumsum.js",
  },
];

{
  const original = await readFile(EXTRACT_TARGET, "utf8");
  let patched = original;
  const applied = [];

  for (const fix of EXTRACT_IMPORT_FIX) {
    if (fix.from.test(patched)) {
      patched = patched.replace(fix.from, fix.to);
      applied.push(fix.note);
    }
    fix.from.lastIndex = 0;
  }

  if (applied.length) {
    await writeFile(EXTRACT_TARGET, patched);
    console.log(`[vendor] patched mindar-extract/extract.js:`);
    for (const note of applied) console.log(`         - ${note}`);
  } else {
    console.log("[vendor] mindar-extract/extract.js: no patching needed");
  }
}

// --------------------------------------------------------- import map + manifest
const importMap = {
  imports: {
    three: "/vendor/three.shim.js",
    "three/addons/": "/vendor/three-addons/",
  },
};
await writeFile(
  join(vendorDir, "import-map.json"),
  JSON.stringify(importMap, null, 2)
);
console.log("[vendor] ok  import-map.json");

if (problems.length) {
  console.error("\n[vendor] FAILED:");
  for (const p of problems) console.error(`  - ${p}`);
  process.exitCode = 1;
} else {
  console.log("\n[vendor] done.");
}
